[py][wx] ModChecker fixes and outstanding issue:
[py] Pass `urllib.parser.quote` the unicode string, no need to encode
[wx] constant errors from activex controls in wxPython:

Traceback (most recent call last):
  File "..\.venv\lib\site-packages\wx\lib\activex.py", line 154, in MSWTranslateMessage
    res = self.ipao.TranslateAccelerator(msg)
OSError: exception: access violation reading 0x0000000018DEEA90

Some googling turned up this:
https://stackoverflow.com/questions/47670838/oserror-exception-access-violation-in-iewin-iehtmlwindow

The workaround mentioned there does *seem* to work, but I don't know enough
about the internal workings of wxPython to be sure no bad side effects
are happening.