[py3] Fix for changes to getttext
Traceback (most recent call last):
  File "..\Mopy\bash\bash.py", line 54, in _import_bolt
    from . import bolt  # bass.language must be set
  File "..\Mopy\bash\bolt.py", line 383, in <module>
    initTranslator(bass.language)
  File "..\Mopy\bash\bolt.py", line 378, in initTranslator
    trans.install(str=True)
TypeError: install() got an unexpected keyword argument 'str'