[py3] types.ClassType no longer exists
Traceback (most recent call last):
  File "..\Mopy\bash\bash.py", line 282, in _main
    from . import basher, balt
  File "..\Mopy\bash\basher\__init__.py", line 64, in <module>
    from types import ClassType
ImportError: cannot import name 'ClassType' from 'types' (C:\Code\Python\3.8\lib\types.py)

Fix:
https://stackoverflow.com/questions/529240/what-happened-to-types-classtype-in-python-3