[wx] `IconBundle.AddIconFromFile` -> `IconBundle.AddIcon`
Traceback (most recent call last):
  File "..\Mopy\bash\bash.py", line 185, in main
    _main(opts)
  File "..\Mopy\bash\bash.py", line 361, in _main
    app.Init() # Link.Frame is set here !
  File "..\Mopy\bash\basher\__init__.py", line 4038, in Init
    self.InitResources()
  File "..\Mopy\bash\basher\__init__.py", line 4064, in InitResources
    Resources.bashBlue = Resources.bashBlue.GetIconBundle()
  File "..\Mopy\bash\balt.py", line 216, in GetIconBundle
    self.iconBundle.AddIconFromFile(
AttributeError: 'IconBundle' object has no attribute 'AddIconFromFile'