UpdateReferences._record_types -> we have to use getReadWriteClasses EEE
Fixup MreRecord.listTypes is not set when we import oblivion/patchers yak! SSS

Error! Unable to start Wrye Bash.

Please ensure Wrye Bash is correctly installed.

Traceback (most recent call last):
  File "bash\bash.py", line 271, in _main
    bashIni, bush_game, game_ini_path = _detect_game(opts, bash_ini_path)
  File "bash\bash.py", line 386, in _detect_game
    bush_game = _import_bush_and_set_game(opts, bashIni)
  File "bash\bash.py", line 398, in _import_bush_and_set_game
    ret, game_icons = bush.detect_and_set_game(opts.oblivionPath, bashIni)
  File "bash\bush.py", line 185, in detect_and_set_game
    __setGame(gamename, u' Using %(gamename)s game:')
  File "bash\bush.py", line 176, in __setGame
    game.init()
  File "bash\game\oblivion\__init__.py", line 238, in init
    cls._dynamic_import_modules(__name__)
  File "bash\game\__init__.py", line 517, in _dynamic_import_modules
    package=package_name)
  File "C:\_\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "Wrye Bash Launcher.pyw", line 76, in load_module
    exec compile(code, initfile, 'exec') in mod.__dict__
  File "bash\game\oblivion\patcher\__init__.py", line 31, in <module>
    from .importers import RoadImporter, CBash_RoadImporter
  File "Wrye Bash Launcher.pyw", line 63, in load_module
    mod = imp.load_source(fullname,filename+ext,fp)
  File "bash\game\oblivion\patcher\importers.py", line 27, in <module>
    from ....patcher.patchers.base import AImportPatcher, CBash_ImportPatcher, \
  File "Wrye Bash Launcher.pyw", line 63, in load_module
    mod = imp.load_source(fullname,filename+ext,fp)
  File "bash\patcher\patchers\base.py", line 156, in <module>
    class UpdateReferences(AUpdateReferences,ListPatcher):
  File "bash\patcher\patchers\base.py", line 158, in UpdateReferences
    MreRecord.simpleTypes | ({'CELL', 'WRLD', 'REFR', 'ACHR', 'ACRE'}))
ImportError: caused by ImportError(u'caused by ImportError(u\'caused by TypeError("unsupported operand type(s) for |: \\\'NoneType\\\' and \\\'set\\\'",)\',)',)

@@ -138,6 +138,3 @@ class CBash_PatchMerger(APatchMerger, CBash_ListPatcher): pass
 class UpdateReferences(AUpdateReferences,ListPatcher):
-    _read_write_records = tuple(
-        MreRecord.simpleTypes | ({'CELL', 'WRLD', 'REFR', 'ACHR', 'ACRE'}))

-    #--Patch Phase ------------------------------------------------------------
     def __init__(self, p_name, p_file, p_sources):
@@ -149,2 +146,10 @@ def __init__(self, p_name, p_file, p_sources):

+    def getReadClasses(self):
+        return tuple(
+            MreRecord.simpleTypes | ({'CELL', 'WRLD', 'REFR', 'ACHR', 'ACRE'}))
+
+    def getWriteClasses(self):
+        return tuple(
+            MreRecord.simpleTypes | ({'CELL', 'WRLD', 'REFR', 'ACHR', 'ACRE'}))
+
     def readFromText(self,textPath):

TODO: move to another file that is not imported in game/*/patcher

srcs are always present