tweaks WIP Race Names needs Review EEE split out _all_tweaks rename TTT
Race moved to next commit

TTT why was

-    if bush.game.fsName == u'Oblivion':
-        tweaks = sorted([
+    @classmethod

used??

Names - what's the deal with bodyTags - they must be moved to game/
anyway - CBash_NamesTweaker and bodyTags?
Race: when is this enabled/active??

bush import FFF

Fix for GLOB traceback: TTT

Traceback (most recent call last):
  File "bash\gui\events.py", line 167, in _post
    result = listener(*listener_args)
  File "bash\balt.py", line 1521, in _conversation_wrapper
    return func(*args, **kwargs)
  File "bash\basher\patcher_dialog.py", line 202, in PatchExecute
    patchFile.buildPatch(log,SubProgress(progress,0.8,0.9))#no speeding needed/really possible (less than 1/4 second even with large LO)
  File "bash\patcher\patch_files.py", line 334, in buildPatch
    patcher.buildPatch(log,SubProgress(subProgress,index))
  File "bash\patcher\patchers\multitweak_settings.py", line 242, in buildPatch

  File "bash\patcher\patchers\multitweak_settings.py", line 42, in buildPatch
    value = self.choiceValues[self.chosen][0]
AttributeError: 'MobBase' object has no attribute 'records'
Breakpoint reached: Any exception

Process finished with exit code -1

This fixes it - introduced in

tweaks WIP Race Names needs Review EEE split out _all_tweaks rename TTT

(currently 48a97c61dac4532b334235ba319dc50e168b03ba)

where instead of returning the patcher classes in
patcher.patchers.base.MultiTweaker.getReadClasses I return the enabled
tweaks' tweak_read_classes - unfortunately GlobalsTweak did not define
those so the GLOB MobObjects was not added to the patch file, MobBase
was added instead

Threw in AClothesTweak tweak_read_classes which would probably blow
also - still this is a WIP -investigate what happens with
patcher.patchers.multitweak_settings.GmstTweaker.scanModFile

    def scanModFile(self,modFile,progress):
        mapper = modFile.getLongMapper()
        for blockType in self._read_write_records:
            if blockType not in modFile.tops: continue
            modBlock = getattr(modFile,blockType)
            patchBlock = getattr(self.patchFile,blockType) <-- GMST not loaded here

and ofc naming

ANamesTweak_BodyTag remains a mystery